import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');

// Worldwide standard: Semantic Versioning MAJOR.MINOR.PATCH.
// ONE format used verbatim everywhere — package.json (exe + auto-update),
// Android versionName (Play listing), welcome footer, installer filename.
// Usage: node scripts/bump-version.mjs [patch|minor|major]  (default patch)
const level = (process.argv[2] || 'patch').toLowerCase();
if (level !== 'patch' && level !== 'minor' && level !== 'major') {
  console.error('[version] Usage: node scripts/bump-version.mjs [patch|minor|major]');
  process.exit(1);
}

const now = new Date();

const pkgPath = path.join(root, 'package.json');
const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));

const vm = String(pkg.version || '').match(/^(\d+)\.(\d+)\.(\d+)$/);
if (!vm) {
  console.error('[version] package.json version must already be semver MAJOR.MINOR.PATCH, found: ' + pkg.version);
  process.exit(1);
}
let major = parseInt(vm[1], 10);
let minor = parseInt(vm[2], 10);
let patch = parseInt(vm[3], 10);
if (level === 'major') { major += 1; minor = 0; patch = 0; }
else if (level === 'minor') { minor += 1; patch = 0; }
else { patch += 1; }
if (minor > 999 || patch > 999) {
  console.error('[version] minor/patch must stay below 1000 (Android versionCode mapping). Bump ' + (patch > 999 ? 'minor' : 'major') + ' instead.');
  process.exit(1);
}

const version = major + '.' + minor + '.' + patch;
// Android versionCode must be a single increasing integer: derive it from
// the semver parts so both numbers can never disagree.
const versionCode = major * 1000000 + minor * 1000 + patch;
const buildTime = now.toISOString();

pkg.version = version;
delete pkg.buildId;
writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');

// android/ only exists after `npx cap add android` — skip stamping until then.
const gradlePath = path.join(root, 'android', 'app', 'build.gradle');
if (existsSync(gradlePath)) {
  let gradle = readFileSync(gradlePath, 'utf8');
  const next = gradle
    .replace(/versionCode \d+/, 'versionCode ' + versionCode)
    .replace(/versionName "[^"]*"/, 'versionName "' + version + '"');
  if (next === gradle || next.indexOf('versionCode ' + versionCode) < 0 || next.indexOf('versionName "' + version + '"') < 0) {
    console.error('[version] Could not stamp android/app/build.gradle (patterns not found).');
    process.exit(1);
  }
  writeFileSync(gradlePath, next);
  console.log('[version] android code : ' + versionCode);
} else {
  console.log('[version] android/ not present yet - versionCode will apply after `npx cap add android`.');
}

const infoPath = path.join(root, 'src', 'buildInfo.js');
writeFileSync(infoPath,
  '// GENERATED by scripts/bump-version.mjs - do not edit by hand.\n' +
  'export const BUILD_ID = ' + JSON.stringify(version) + ';\n' +
  'export const BUILD_TIME = ' + JSON.stringify(buildTime) + ';\n');

console.log('[version] version      : ' + version + ' (' + level + ' bump)');
console.log('[version] built at     : ' + buildTime);
