// Stamp BUILD_TIME on EVERY build (even without a version bump).
// bump-version.mjs only refreshes src/buildInfo.js when you pass patch|minor|major,
// so same-version redeploys kept the old timestamp and the welcome footer looked stale.
// This script keeps BUILD_ID = package.json version and refreshes BUILD_TIME = now.
// Usage: node scripts/stamp-build.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');

const pkgPath = path.join(root, 'package.json');
const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
const version = String(pkg.version || '0.0.0');
const buildTime = new Date().toISOString();

const infoPath = path.join(root, 'src', 'buildInfo.js');
writeFileSync(infoPath,
  '// GENERATED by scripts/stamp-build.mjs - do not edit by hand.\n' +
  'export const BUILD_ID = ' + JSON.stringify(version) + ';\n' +
  'export const BUILD_TIME = ' + JSON.stringify(buildTime) + ';\n');

console.log('[stamp] BUILD_ID=' + version + ' BUILD_TIME=' + buildTime);
